# Generated by Django 3.2.3 on 2023-09-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230921_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
