# Generated by Django 3.2.3 on 2023-09-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_delete_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='measurement_unit',
        ),
    ]
