# Generated by Django 3.2.3 on 2023-09-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230925_1952'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientrecipe',
            name='ingredientrecipe_unique',
        ),
    ]
