# Generated by Django 3.2.3 on 2023-09-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_follow',
        ),
    ]
