# Generated by Django 3.2.3 on 2023-09-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230927_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='following',
            new_name='author',
        ),
    ]
